### ISSUE TITLE
citree == ctree?

### ISSUE THREAD

**Issue by krey** [rmill040/citrees#1]
Hi @rmill040 

Are the models implemented here the same as described in Hothorn, Hornik and Zeileis "Unbiased recursive partitioning: A conditional inference framework"?

Many thanks for putting this online,

krey

**Comment by rmill040** [comment]
Hi @krey,

The models are not identical but have the same flavor. Both implementations focus on iterating between feature selection and split selection. From a high level, this implementation is similar to random forests but first performing feature selection and then finding the best split on that feature using impurity measures such as the gini index, mean squared error, etc. Compared to ctree described in Hothorn et al., I added some extra hyperparameters for early stopping and variable muting that help in feature selection.

**Comment by krey** [comment]
I'm trying to figure out what this line does https://github.com/rmill040/citrees/blob/62c5e767dc38f714b8d7ee75b81d54b43be99def/citrees/selectors.py#L48

We take a predictor `X_j` and the dependent variable `Y`, concatenate them and then shuffle?
But then some of the xs become ys and vice versa.

Am I reading it correctly?

As far as I understand, Hothorn et al. only shuffle the ys.

**Comment by rmill040** [comment]
The permutation lemma for correlations is to just shuffle y in (x,y) pairs, however, aggregating and shuffling the array yields identical results in every case I've seen and tested. Good catch regardless -- I updated the code to match the shuffling of only y for correlation permutation tests.
